# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

idndslimits:
    maxarea:
        - 2.5
    minarea:
        - 0.02
    step:
        - 0.05

params:
    rho:
        - 5000
    binsize:
        - 0.002
    delta:
        - 0.1

paramsdata:
    rho:
        - 5000
    binsize:
        - 0.005
    its:
        - 5000
    quantile:
        - 0.9
    minvaf:
        - 0.008

log_dir: "logs"

patient:
    - PD31182

metadata:
    oesophagus:
        - data/oesophagus/donorinfo.csv
    skin:
        - data/skin/donorinfo.csv

stansingularity: "/data/BCI-EvoCa2/marc/singularity/dnds-clonesize-R-container_latest.sif"

#number of times to resample the simulations
nsamplesnormal: 100

#filtering parameters for oesophagus and skin data
mutationcutoff: 7
rsqcutoff: 0.6
